name: CD - Stage 2 (Staging)
on:
  workflow_run:
    workflows: [ "CI - Stage 1 (testing branch)" ]
    types: [ "completed" ]
    branches: [ "testing" ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "ACR image tag to deploy (default: testing-latest)"
        required: false
        type: string
      namespace_suffix:
        description: "Override namespace suffix (default: short SHA)"
        required: false
        type: string

env:
  REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}

concurrency:
  group: staging-${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy-staging:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Compute image TAG and Namespace
        id: meta
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            SHA="${{ github.event.workflow_run.head_sha }}"
          else
            SHA="${{ github.sha }}"
          fi
          SHORT="${SHA:0:7}"

          INPUT_TAG="${{ inputs.image_tag || '' }}"
          if [ -n "$INPUT_TAG" ]; then
            TAG="$INPUT_TAG"
          else
            TAG="testing-latest"
          fi

          NS_SUFFIX="${{ inputs.namespace_suffix || '' }}"
          if [ -z "$NS_SUFFIX" ]; then
            NS_SUFFIX="$SHORT"
          fi
          NS="staging-$NS_SUFFIX"

          echo "TAG=$TAG"   >> "$GITHUB_OUTPUT"
          echo "NS=$NS"     >> "$GITHUB_OUTPUT"
          echo "REG=${{ env.REGISTRY }}" >> "$GITHUB_OUTPUT"
          echo "Using REG=${{ env.REGISTRY }}, TAG=$TAG, NS=$NS"

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}

      - name: Create staging namespace
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          kubectl get ns "$NS" >/dev/null 2>&1 || kubectl create ns "$NS"

      - name: Apply k8s manifests to staging
        working-directory: k8s
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          kubectl -n "$NS" apply -f configmaps.yaml
          kubectl -n "$NS" apply -f secrets.yaml || true
          kubectl -n "$NS" apply -f rabbitmq.yaml
          kubectl -n "$NS" apply -f product-db.yaml
          kubectl -n "$NS" apply -f order-db.yaml
          kubectl -n "$NS" apply -f customer-db.yaml
          kubectl -n "$NS" apply -f product-service.yaml
          kubectl -n "$NS" apply -f order-service.yaml
          kubectl -n "$NS" apply -f customer-service.yaml
          kubectl -n "$NS" apply -f frontend.yaml || true

      - name: Wait for DB deployments (before app rollouts)
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          kubectl -n "$NS" rollout status deploy/product-db-deployment-w10-aks   --timeout=300s || true
          kubectl -n "$NS" rollout status deploy/order-db-deployment-w10-aks     --timeout=300s || true
          kubectl -n "$NS" rollout status deploy/customer-db-deployment-w10-aks  --timeout=300s || true

      - name: Pre-scale app deployments to 2 replicas (avoid deadlock)
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          kubectl -n "$NS" scale deploy/product-service-w10-aks  --replicas=2 || true
          kubectl -n "$NS" scale deploy/order-service-w10-aks    --replicas=2 || true
          kubectl -n "$NS" scale deploy/customer-service-w10-aks --replicas=2 || true
          # Wait a bit to let extra replicas schedule
          sleep 10

      - name: Set images to computed tag
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          REG="${{ steps.meta.outputs.REG }}"
          TAG="${{ steps.meta.outputs.TAG }}"
          kubectl -n "$NS" set image deployment/product-service-w10-aks \
            product-service-container="$REG/product_service:$TAG"
          kubectl -n "$NS" set image deployment/order-service-w10-aks \
            order-service-container="$REG/order_service:$TAG"
          kubectl -n "$NS" set image deployment/customer-service-w10-aks \
            customer-service-container="$REG/customer_service:$TAG"
          kubectl -n "$NS" set image deployment/frontend-w10-aks \
            frontend-container="$REG/frontend:$TAG" || true

      - name: Wait for rollouts
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          kubectl -n "$NS" rollout status deployment/product-service-w10-aks --timeout=600s
          kubectl -n "$NS" rollout status deployment/order-service-w10-aks --timeout=600s
          kubectl -n "$NS" rollout status deployment/customer-service-w10-aks --timeout=600s
          kubectl -n "$NS" rollout status deployment/frontend-w10-aks --timeout=600s || true

      - name: Dump diagnostics on failure
        if: failure()
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          echo "=== Deployments"; kubectl -n "$NS" get deploy -o wide || true
          echo "=== ReplicaSets"; kubectl -n "$NS" get rs -o wide || true
          echo "=== Pods";        kubectl -n "$NS" get pods -o wide --show-labels || true
          echo "=== Events";      kubectl -n "$NS" get events --sort-by=.lastTimestamp | tail -n 200 || true
          for d in product-service-w10-aks order-service-w10-aks customer-service-w10-aks; do
            echo "--- describe deploy/$d"; kubectl -n "$NS" describe deploy "$d" || true
          done
          for p in $(kubectl -n "$NS" get pods -o name); do
            echo "--- describe $p"; kubectl -n "$NS" describe "$p" || true
          done

      - name: Acceptance checks (/health)
        run: |
          set -e
          NS="${{ steps.meta.outputs.NS }}"
          # Port-forward services and probe /health endpoints
          kubectl -n "$NS" port-forward svc/product-service-w10-aks 18000:8000 >/dev/null 2>&1 &
          PFPID1=$!
          kubectl -n "$NS" port-forward svc/order-service-w10-aks 18001:8000 >/dev/null 2>&1 &
          PFPID2=$!
          kubectl -n "$NS" port-forward svc/customer-service-w10-aks 18002:8000 >/dev/null 2>&1 &
          PFPID3=$!
          # give port-forwards time to bind
          sleep 5
          curl -sf http://127.0.0.1:18000/health | cat
          curl -sf http://127.0.0.1:18001/health | cat
          curl -sf http://127.0.0.1:18002/health | cat
          kubectl -n "$NS" port-forward svc/frontend-w10-aks 18003:80 >/dev/null 2>&1 &
          PFPID4=$!
          sleep 2
          curl -sf http://127.0.0.1:18003/ | head -n 1 | cat || true
          # cleanup port-forward background jobs
          kill $PFPID1 $PFPID2 $PFPID3 $PFPID4 || true

      - name: Basic smoke (pods up)
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          kubectl -n "$NS" get pods
          kubectl -n "$NS" get svc

      - name: Scale app deployments back to 1 (optional)
        run: |
          NS="${{ steps.meta.outputs.NS }}"
          kubectl -n "$NS" scale deploy/product-service-w10-aks  --replicas=1 || true
          kubectl -n "$NS" scale deploy/order-service-w10-aks    --replicas=1 || true
          kubectl -n "$NS" scale deploy/customer-service-w10-aks --replicas=1 || true

      - name: Destroy staging environment
        if: always()
        run: |
          kubectl delete ns "${{ steps.meta.outputs.NS }}" --wait=false